### ISSUE TITLE
Add command to save logcat into file

### ISSUE THREAD

**Issue by HlebMaliborski** [alexander-kulikovskii/toster#42]
adb logcat
adb logcat -c // clear // The parameter -c will clear the current logs on the device.
adb logcat -d > [path_to_file] // Save the logcat output to a file on the local system.
adb bugreport > [path_to_file] // Will dump the whole device information like dumpstate, dumpsys and logcat output.

We can use such functions to manipulate with device logcat. 
Probably it should be the lastest step in execution of commands to see full information after evaluation.

**Comment by alexander-kulikovskii** [comment]
closed with #134
